// Actions Types

// List
export const LIST_REQUEST = 'PORTFOLIO/LIST/REQUEST'
export const LIST_RESPONSE = 'PORTFOLIO/LIST/RESPONSE'
export const QUOTE_RESPONSE = 'PORTFOLIO/QUOTE/RESPONSE'
export const STOCK_RESPONSE = 'PORTFOLIO/STOCK/RESPONSE'
export const DATA_RESPONSE = 'PORTFOLIO/DATA/RESPONSE'
export const LIST_DONE = 'PORTFOLIO/LIST/DONE'
export const LIST_RESET = 'PORTFOLIO/LIST/RESET'
